import json
import logging
import re

from google import genai
from google.genai import types
from prompt_template import NOTEBOOK_PROMPT_TEMPLATE

logger = logging.getLogger("paper_to_notebook")

DANGEROUS_PATTERNS = [
    "os.system", "subprocess", "eval(", "exec(", "__import__",
    "shutil.rmtree", "curl ", "wget ", "rm -rf",
]

SAFETY_DISCLAIMER_CELL = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# ⚠️ Safety Notice\n",
        "**This notebook was generated by an AI model.** "
        "Please review all code cells carefully before executing them. "
        "The code has been automatically scanned for dangerous patterns, "
        "but AI-generated code may still contain errors or unexpected behavior.\n",
        "\n",
        "**Do not run this notebook on sensitive systems without thorough review.**"
    ],
    "id": "safety-disclaimer"
}


def _scan_code_cells(nb: dict) -> dict:
    """Scan code cells for dangerous patterns and add warnings."""
    for cell in nb.get("cells", []):
        if cell.get("cell_type") != "code":
            continue
        source = "".join(cell.get("source", []))
        found = [p for p in DANGEROUS_PATTERNS if p in source]
        if found:
            warning = f"# ⚠️ WARNING: This cell contains potentially dangerous patterns: {', '.join(found)}\n# Review carefully before running.\n"
            if isinstance(cell["source"], list):
                cell["source"].insert(0, warning)
            else:
                cell["source"] = warning + cell["source"]
            logger.warning("Dangerous pattern found in generated code: %s", found)
    return nb


def _extract_json(text: str) -> str:
    """Extract JSON from Gemini response, handling markdown code fences."""
    # Try to find JSON in code fences first
    match = re.search(r"```(?:json)?\s*\n(.*?)\n```", text, re.DOTALL)
    if match:
        return match.group(1)
    # Otherwise assume the whole response is JSON
    return text.strip()


def _validate_notebook(nb: dict) -> dict:
    """Ensure notebook has required ipynb structure."""
    if "nbformat" not in nb:
        nb["nbformat"] = 4
    if "nbformat_minor" not in nb:
        nb["nbformat_minor"] = 5
    if "metadata" not in nb:
        nb["metadata"] = {}
    if "cells" not in nb:
        raise ValueError("Notebook JSON missing 'cells' array")

    # Ensure Colab metadata
    nb["metadata"].setdefault("kernelspec", {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    })
    nb["metadata"].setdefault("colab", {"provenance": [], "gpuType": "T4"})
    nb["metadata"].setdefault("accelerator", "GPU")

    # Validate each cell and assign IDs
    for i, cell in enumerate(nb["cells"]):
        if cell.get("cell_type") == "code":
            cell.setdefault("execution_count", None)
            cell.setdefault("outputs", [])
        cell.setdefault("metadata", {})
        cell.setdefault("id", f"cell-{i}")
        # Ensure source is a list of strings
        if isinstance(cell.get("source"), str):
            cell["source"] = [cell["source"]]

    return nb


def generate_notebook(paper_text: str, api_key: str) -> dict:
    """Send paper text to Gemini and return a valid .ipynb notebook dict."""
    client = genai.Client(api_key=api_key)

    prompt = NOTEBOOK_PROMPT_TEMPLATE.format(paper_text=paper_text)

    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=prompt,
        config=types.GenerateContentConfig(
            temperature=0.2,
            max_output_tokens=8192,
            response_mime_type="application/json",
        ),
    )

    raw_text = response.text
    json_str = _extract_json(raw_text)

    try:
        notebook = json.loads(json_str)
    except json.JSONDecodeError as e:
        raise ValueError(f"Gemini returned invalid JSON: {e}\nResponse: {raw_text[:500]}")

    notebook = _validate_notebook(notebook)
    notebook = _scan_code_cells(notebook)
    # Insert safety disclaimer as the first cell
    notebook["cells"].insert(0, SAFETY_DISCLAIMER_CELL)
    return notebook
